[build]
  command = "npm run build:all"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@upstash/redis", "stripe", "openai"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[dev]
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"